import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StyledRoot } from "./StyledRoot";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "FAC ERP",
    description: "Generated by create next app",
};

export const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => (
    <html lang="pt-BR">
        <body className={inter.className}>
            <AppRouterCacheProvider>    
                <StyledRoot>
                    {children}
                </StyledRoot>
            </AppRouterCacheProvider>
        </body>
    </html>
);

export default RootLayout;

